2016-12-15 16:51:47,292 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2016-12-15 16:51:50,078 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2016-12-15 16:51:50,541 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2016-12-15 16:51:50,570 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2016-12-15 16:51:50,762 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 16:51:56,165 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2016-12-15 16:51:56,166 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
2016-12-15 16:52:00,348 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2016-12-15 16:52:01,964 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2016-12-15 16:52:37,743 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 16:52:49,054 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 17:06:06,790 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2016-12-15 17:06:09,031 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2016-12-15 17:06:09,687 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2016-12-15 17:06:09,709 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2016-12-15 17:06:09,814 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 17:06:14,292 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2016-12-15 17:06:14,293 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
2016-12-15 17:06:14,729 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2016-12-15 17:06:21,621 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "uthrottle"}']'
2016-12-15 17:06:21,622 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '58', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from sumac.canonical.com', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache', 'etag': '"0836fb9653102d1f574f7947862fb056"', 'cache-control': 'max-age=300', 'date': 'Thu, 15 Dec 2016 11:36:21 GMT', 'content-type': 'text/html; charset=utf-8'}
'
2016-12-15 17:06:21,622 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '58', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from sumac.canonical.com', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache', 'etag': '"0836fb9653102d1f574f7947862fb056"', 'cache-control': 'max-age=300', 'date': 'Thu, 15 Dec 2016 11:36:21 GMT', 'content-type': 'text/html; charset=utf-8'}

2016-12-15 17:06:21,622 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '58', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from sumac.canonical.com', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache', 'etag': '"0836fb9653102d1f574f7947862fb056"', 'cache-control': 'max-age=300', 'date': 'Thu, 15 Dec 2016 11:36:21 GMT', 'content-type': 'text/html; charset=utf-8'}

2016-12-15 17:06:44,115 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2016-12-15 17:09:57,623 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 17:10:05,419 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 20:17:06,488 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2016-12-15 20:17:09,574 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2016-12-15 20:17:10,379 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2016-12-15 20:17:10,396 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2016-12-15 20:17:10,550 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 20:17:12,303 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2016-12-15 20:17:12,322 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
2016-12-15 20:17:16,708 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2016-12-15 20:17:25,303 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2016-12-15 20:17:54,152 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 20:18:05,136 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 20:37:42,593 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2016-12-15 20:37:45,371 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2016-12-15 20:37:45,386 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2016-12-15 20:37:45,592 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 20:37:48,793 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2016-12-15 20:37:48,808 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
2016-12-15 20:37:56,879 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2016-12-15 20:38:09,995 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2016-12-15 20:39:19,591 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-12-15 20:39:28,953 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
